import { useState } from 'react';
import { COLORS, PROVIDERS, providerById } from '@forge/core';
import type { ProviderId } from '@forge/core';
import { Spinner, mono } from '@forge/ui';
import type { MobileSession } from './session.js';
import { APP_VERSION } from './version.js';

const A = COLORS.accent;

/**
 * First run. Three steps, none of them skippable-into-a-fake-state: name the
 * project, then either connect a provider or continue without one — in which
 * case the app plainly says generation is off until a key is added.
 */
export function Onboarding({ s }: { s: MobileSession }) {
  const [step, setStep] = useState<'welcome' | 'project' | 'provider'>('welcome');
  const [name, setName] = useState('');
  const [provider, setProvider] = useState<ProviderId>('meshy');
  const [key, setKey] = useState('');
  const [checking, setChecking] = useState(false);
  const [result, setResult] = useState<{ ok: boolean; message: string } | null>(null);

  const connect = async () => {
    const p = providerById(provider);
    if (!p || !key.trim()) return;
    setChecking(true);
    setResult(null);
    const check = await p.validateKey(key.trim());
    setResult(check);
    setChecking(false);
    if (check.ok) {
      await s.connectProvider({ provider, apiKey: key.trim() });
      await s.finishOnboarding();
    }
  };

  const finishWithoutKey = async () => {
    await s.finishOnboarding();
  };

  /**
   * Naming the project is a convenience, not a requirement — everywhere it is
   * shown falls back to "Your project", and Settings can set it later. Making
   * it mandatory just put a form between the user and the app.
   */
  const continuePastName = () => {
    const trimmed = name.trim();
    if (trimmed) s.updateSettings({ projectName: trimmed });
    setStep('provider');
  };

  return (
    <div
      style={{
        position: 'absolute',
        inset: 0,
        display: 'flex',
        flexDirection: 'column',
        padding: '28px 20px calc(20px + env(safe-area-inset-bottom))',
        background: COLORS.canvas,
        overflowY: 'auto',
      }}
    >
      {step === 'welcome' && (
        <>
          <div style={{ flex: 1 }} />
          <div
            style={{
              width: 64,
              height: 64,
              borderRadius: 16,
              background: COLORS.surface,
              border: `1px solid ${COLORS.panelBorder}`,
              display: 'grid',
              placeItems: 'center',
              fontSize: 28,
              fontWeight: 600,
              color: A,
              marginBottom: 20,
            }}
          >
            F
          </div>
          <h1 style={{ fontSize: 24, fontWeight: 600, margin: 0 }}>Forge</h1>
          <p style={{ fontSize: 14, color: COLORS.text2, lineHeight: 1.6, margin: '10px 0 0' }}>
            Describe an object or photograph one, and Forge turns it into a 3D model you can drop
            into your game.
          </p>
          <p style={{ fontSize: 12, color: COLORS.muted, lineHeight: 1.6, margin: '14px 0 0' }}>
            Models are generated by a 3D provider you connect with your own API key, and are stored
            on this device. Nothing is uploaded anywhere else.
          </p>
          <div style={{ flex: 1 }} />
          <button type="button" onClick={() => setStep('project')} style={primary}>
            Get started
          </button>
          <div
            style={{
              textAlign: 'center',
              fontFamily: mono,
              fontSize: 10,
              color: COLORS.disabled,
              marginTop: 14,
            }}
          >
            Forge {APP_VERSION}
          </div>
        </>
      )}

      {step === 'project' && (
        <>
          <h2 style={{ fontSize: 18, fontWeight: 600, margin: '20px 0 0' }}>Name your project</h2>
          <p style={{ fontSize: 12, color: COLORS.muted, lineHeight: 1.6, margin: '8px 0 18px' }}>
            Everything you make gets grouped under this. Optional — you can name it later in
            Settings.
          </p>
          <input
            value={name}
            onChange={(e) => setName(e.target.value)}
            placeholder="e.g. Dustline"
            autoFocus
            enterKeyHint="next"
            onKeyDown={(e) => {
              if (e.key === 'Enter') continuePastName();
            }}
            style={input}
          />
          <div style={{ flex: 1 }} />
          <button type="button" onClick={continuePastName} style={primary}>
            {name.trim() ? 'Continue' : 'Skip for now'}
          </button>
        </>
      )}

      {step === 'provider' && (
        <>
          <h2 style={{ fontSize: 18, fontWeight: 600, margin: '20px 0 0' }}>
            Connect a 3D provider
          </h2>
          <p style={{ fontSize: 12, color: COLORS.muted, lineHeight: 1.6, margin: '8px 0 16px' }}>
            Forge generates models through your own account with one of these services. Both are
            paid and charge credits per model. Your key stays on this device.
          </p>

          <div style={{ display: 'flex', gap: 8, marginBottom: 14 }}>
            {PROVIDERS.map((p) => {
              const on = p.id === provider;
              return (
                <button
                  key={p.id}
                  type="button"
                  onClick={() => {
                    setProvider(p.id);
                    setKey('');
                    setResult(null);
                  }}
                  style={{
                    flex: 1,
                    padding: '12px 0',
                    borderRadius: 10,
                    border: `1px solid ${on ? A : COLORS.inputBorder}`,
                    background: on ? COLORS.accentTint : 'transparent',
                    color: on ? A : COLORS.text2,
                    fontWeight: on ? 600 : 400,
                    fontSize: 13,
                    cursor: 'pointer',
                  }}
                >
                  {p.name}
                </button>
              );
            })}
          </div>

          <input
            value={key}
            onChange={(e) => {
              setKey(e.target.value);
              setResult(null);
            }}
            placeholder={providerById(provider)?.keyPlaceholder}
            autoComplete="off"
            autoCapitalize="none"
            spellCheck={false}
            style={{ ...input, fontFamily: mono }}
          />

          <a
            href={providerById(provider)?.keysUrl}
            target="_blank"
            rel="noreferrer"
            style={{ fontSize: 11, marginTop: 10, display: 'inline-block' }}
          >
            Where do I get a {providerById(provider)?.name} key? ↗
          </a>

          {result && (
            <div
              style={{
                marginTop: 12,
                padding: 10,
                borderRadius: 8,
                fontSize: 11,
                lineHeight: 1.5,
                background: result.ok ? COLORS.okTint : 'rgba(255,95,87,.12)',
                color: result.ok ? COLORS.ok : COLORS.danger,
              }}
            >
              {result.message}
            </div>
          )}

          <div style={{ flex: 1, minHeight: 20 }} />

          <button
            type="button"
            onClick={() => void connect()}
            disabled={!key.trim() || checking}
            style={{
              ...primary,
              background: key.trim() && !checking ? A : '#8a5a22',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: 9,
            }}
          >
            {checking && <Spinner size={13} color={COLORS.ink} />}
            {checking ? 'Checking your key…' : 'Connect'}
          </button>

          <button type="button" onClick={() => void finishWithoutKey()} style={secondary}>
            Skip for now
          </button>
          <p style={{ fontSize: 11, color: COLORS.muted, lineHeight: 1.5, margin: '10px 0 0' }}>
            Without a key you can still import <code>.glb</code> files you already have, view them,
            and export them. Generating is off until you add one.
          </p>
        </>
      )}
    </div>
  );
}

const input = {
  width: '100%',
  height: 46,
  padding: '0 14px',
  borderRadius: 10,
  background: COLORS.input,
  border: `1px solid ${COLORS.inputBorder}`,
  color: COLORS.text,
  fontSize: 14,
} as const;

const primary = {
  width: '100%',
  padding: '14px 0',
  borderRadius: 10,
  border: 'none',
  background: A,
  color: COLORS.ink,
  fontWeight: 600,
  fontSize: 14,
  cursor: 'pointer',
} as const;

const secondary = {
  width: '100%',
  marginTop: 10,
  padding: '13px 0',
  borderRadius: 10,
  border: `1px solid ${COLORS.inputBorder}`,
  background: 'transparent',
  color: COLORS.text2,
  fontSize: 13,
  cursor: 'pointer',
} as const;
