import { useState } from 'react';
import { COLORS } from '@forge/core';
import type { Asset } from '@forge/core';
import { Spinner } from './components.js';

const A = COLORS.accent;

/**
 * Starting points, not a fixed palette — every one of these is just text that
 * gets sent to the provider, and anything typed by hand works the same way.
 */
const SUGGESTIONS = [
  'light skin tone',
  'medium brown skin tone',
  'deep brown skin tone',
  'red hoodie and black jeans',
  'leather jacket',
  'monk robes',
  'weathered armour',
  'clean shaven',
  'short beard',
];

export interface AppearanceProps {
  asset: Asset;
  /** False for an imported file, which has no provider task to repaint. */
  canRestyle: boolean;
  busy: boolean;
  onRestyle: (description: string) => void;
  compact?: boolean;
}

/**
 * Change how a model looks without rebuilding it.
 *
 * Worth being straight about the limits: the provider re-textures the whole
 * model from one description. There is no way to select just the jacket, and
 * skin tone is not a slider — it is a word in a sentence. The mesh itself is
 * untouched, so the character's shape and proportions survive, and the
 * previous look stays in the version history.
 */
export function Appearance({ asset, canRestyle, busy, onRestyle, compact }: AppearanceProps) {
  const [text, setText] = useState('');

  const add = (word: string) =>
    setText((prev) => (prev.trim() ? `${prev.replace(/,\s*$/, '')}, ${word}` : word));

  if (!canRestyle) {
    return (
      <p style={{ fontSize: 11, color: COLORS.muted, lineHeight: 1.6, margin: 0 }}>
        Only models generated by Meshy in this app can be restyled — an imported file has no
        provider task behind it.
      </p>
    );
  }

  return (
    <>
      <p style={{ fontSize: 11, color: COLORS.muted, lineHeight: 1.6, margin: '0 0 10px' }}>
        Describe the whole look and the model is repainted from it. The mesh is not rebuilt, so it
        stays the same character — and the current look stays in the version history.
      </p>

      <textarea
        value={text}
        onChange={(e) => setText(e.target.value)}
        placeholder="e.g. deep brown skin tone, red hoodie, black jeans, worn sneakers"
        rows={compact ? 3 : 2}
        style={{
          width: '100%',
          resize: 'none',
          padding: 10,
          borderRadius: 8,
          background: COLORS.input,
          border: `1px solid ${COLORS.inputBorder}`,
          color: COLORS.text,
          fontSize: 12,
          lineHeight: 1.5,
        }}
      />

      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 5, margin: '9px 0 0' }}>
        {SUGGESTIONS.map((word) => (
          <button
            key={word}
            type="button"
            onClick={() => add(word)}
            style={{
              padding: '5px 9px',
              borderRadius: 999,
              border: `1px solid ${COLORS.inputBorder}`,
              background: 'transparent',
              color: COLORS.text2,
              fontSize: 10,
              cursor: 'pointer',
            }}
          >
            + {word}
          </button>
        ))}
      </div>

      <button
        type="button"
        disabled={!text.trim() || busy}
        onClick={() => {
          onRestyle(text.trim());
          setText('');
        }}
        style={{
          width: '100%',
          marginTop: 11,
          padding: compact ? '12px 0' : '9px 0',
          borderRadius: 8,
          border: 'none',
          background: text.trim() && !busy ? A : COLORS.control,
          color: text.trim() && !busy ? COLORS.ink : COLORS.muted,
          fontWeight: 600,
          fontSize: 12,
          cursor: text.trim() && !busy ? 'pointer' : 'not-allowed',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          gap: 8,
        }}
      >
        {busy && <Spinner size={12} />}
        {busy ? 'Repainting…' : `Repaint ${asset.name}`}
      </button>

      <p style={{ fontSize: 10, color: COLORS.muted, lineHeight: 1.5, margin: '8px 0 0' }}>
        Costs one texture job of provider credits.
      </p>
    </>
  );
}
